import { Injectable } from "@angular/core";
import { Painting } from "../models/painting";

@Injectable({
  providedIn: "root",
})
export class PaintingService {
  private paintings: Painting[] = [
    {
      id: "frame1",
      title: "Andy Warhol is not dead",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "50x64",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame2",
      title: "Oranje figuur",
      artist: "Alexander van den Bosch",
      year: 1985,
      dimensions: "75x54",
      status: "framed",
      type: "drawing",
    },
    {
      id: "rol1",
      artist: "Alexander van den Bosch",
      dimensions: "100x120",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol2",
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "100x138",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "frame3",
      title: "Inferno 4",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "64x50",
      status: "framed",
      type: "drawing",
    },
    {
      id: "frame4",
      artist: "Alexander van den Bosch",
      dimensions: "54x74",
      status: "framed",
      type: "oilpainting",
      note: "Damaged glass",
    },
    {
      id: "frame5",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "47x58",
      status: "framed",
      type: "drawing",
      note: "Damaged glass",
    },
    {
      id: "frame6",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x56",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame7",
      artist: "Alexander van den Bosch",
      dimensions: "70x85",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame8",
      title: "Zeilbootje bij kalme zee",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "121x96",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame9",
      title: "De speelgoedhoek",
      artist: "Alexander van den Bosch",
      year: 1984,
      dimensions: "121x100",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame10",
      title: "IJshockiers",
      artist: "Alexander van den Bosch",
      year: 1984,
      dimensions: "100x120",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame11",
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x140",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame12",
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x140",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "rol3",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol4",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "139x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol5",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "102x141",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol6",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "102x120",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol7",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol8",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol9",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "121x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol10",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "140x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol11",
      artist: "Alexander van den Bosch",
      dimensions: "100x140",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol12",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "121x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol14",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "139x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol13",
      artist: "Alexander van den Bosch",
      dimensions: "141x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol15",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol16",
      artist: "Alexander van den Bosch",
      dimensions: "138x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol17",
      artist: "Alexander van den Bosch",
      dimensions: "126x96",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol18",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol19",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "141x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol20",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol21",
      artist: "Alexander van den Bosch",
      year: 1964,
      dimensions: "137x110",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol22",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "112x112",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol23",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x103",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol24",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "118x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol25",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "111x70",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol26",
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "110x135",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol27",
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "118x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "frame14",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: "frame15",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: "frame16",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: "rol29",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "60x51",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "rol30",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "110x70",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "frame17",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame18",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "75x54",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame19",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame20",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame21",
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "75x54",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame22",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "75x54",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame23",
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "75x50",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame24",
      title: "Fantomas cinema",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "passepartout",
      type: "gouache",
    },
    {
      id: "frame25",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "91x63",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: "frame26",
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame27",
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "frame28",
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame29",
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame30",
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      type: "oilpainting",
    },
    {
      id: "frame31",
      title: "Fantomas cinema",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "47x63",
      status: "passepartout",
      type: "gouache",
    },
    {
      id: "frame32",
      title: "Landschap na zonsondergang",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      type: "gouache",
    },
    {
      id: "frame33",
      title: "Bloesemboompjes",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      type: "gouache",
    },
    {
      id: "frame34",
      title: "Veulen met jong bij onweer",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      type: "gouache",
    },
    {
      id: "frame35",
      title: "Landschap bij zonnig weer",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "framed",
      type: "gouache",
    },
    {
      id: "frame36",
      title: "Vier marionetten",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "56x39",
      status: "framed",
      type: "gouache",
    },
    {
      id: "frame37",
      title: "Landschap met oude molen",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "framed",
      type: "gouache",
    },
    {
      id: "frame38",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame39",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame40",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame41",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame42",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame43",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame44",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame45",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame46",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame47",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      type: "gouache",
    },
    {
      id: "frame48",
      title: "Muze bevredigd",
      artist: "Alexander van den Bosch",
      year: 1964,
      dimensions: "49x34",
      status: "passepartout",
      type: "gouache",
    },
    {
      id: "frame49",
      artist: "Alexander van den Bosch",
      title: "Andy Warhol is not dead",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      type: "drawing",
    },
    {
      id: "frame50",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      type: "drawing",
    },
    {
      id: "frame51",
      title: "Andy Warhol is not dead",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      type: "drawing",
    },
    {
      id: "frame52",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      type: "drawing",
    },
    {
      id: "frame53",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      type: "drawing",
    },
    {
      id: "frame54",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      type: "drawing",
    },
  ];

  getPaintings(): Painting[] {
    return this.paintings;
  }
}
