import { Injectable } from "@angular/core";
import { Painting } from "../models/painting";

@Injectable({
  providedIn: "root",
})
export class PaintingService {
  private paintings: Painting[] = [
    {
      id: "46",
      title: "Andy Warhol is not dead",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "50x64",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "47",
      title: "Oranje figuur",
      artist: "Alexander van den Bosch",
      year: 1985,
      dimensions: "75x54",
      status: "framed",
      type: "drawing",
    },
    {
      id: "1",
      artist: "Alexander van den Bosch",
      dimensions: "100x120",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "2",
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "100x138",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "48",
      title: "Inferno 4",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "64x50",
      status: "framed",
      type: "drawing",
    },
    {
      id: "49",
      artist: "Alexander van den Bosch",
      dimensions: "54x74",
      status: "framed",
      type: "oilpainting",
      note: "Damaged glass",
    },
    {
      id: "50",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "47x58",
      status: "framed",
      type: "drawing",
      note: "Damaged glass",
    },
    {
      id: "51",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x56",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "52",
      artist: "Alexander van den Bosch",
      dimensions: "70x85",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "53",
      title: "Zeilbootje bij kalme zee",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "121x96",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "54",
      title: "De speelgoedhoek",
      artist: "Alexander van den Bosch",
      year: 1984,
      dimensions: "121x100",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "55",
      title: "IJshockiers",
      artist: "Alexander van den Bosch",
      year: 1984,
      dimensions: "100x120",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "56",
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x140",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "57",
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x140",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: "3",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "4",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "139x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "5",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "102x141",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "6",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "102x120",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "7",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "8",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "9",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "121x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "10",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "140x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "11",
      artist: "Alexander van den Bosch",
      dimensions: "100x140",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "12",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "121x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "14",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "139x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "13",
      artist: "Alexander van den Bosch",
      dimensions: "141x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "15",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "16",
      artist: "Alexander van den Bosch",
      dimensions: "138x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "17",
      artist: "Alexander van den Bosch",
      dimensions: "126x96",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "18",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "19",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "141x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "20",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "21",
      artist: "Alexander van den Bosch",
      year: 1964,
      dimensions: "137x110",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "22",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "112x112",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "23",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x103",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "24",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "118x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "25",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "111x70",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "26",
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "110x135",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "27",
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "118x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "58",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: "59",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: "60",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: "61",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "62",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "63",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "64",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "65",
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "66",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "67",
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "75x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "68",
      title: "Fantomas cinema",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "passepartout",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "69",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "91x63",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "70",
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "71",
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "framed",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "72",
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "73",
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "74",
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "75",
      title: "Fantomas cinema",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "47x63",
      status: "passepartout",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "76",
      title: "Landschap na zonsondergang",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "77",
      title: "Bloesemboompjes",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "78",
      title: "Veulen met jong bij onweer",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "79",
      title: "Landschap bij zonnig weer",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "80",
      title: "Vier marionetten",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "56x39",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "81",
      title: "Landschap met oude molen",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "82",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "83",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "84",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "85",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "86",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "87",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "88",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "89",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "90",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "91",
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "92",
      title: "Muze bevredigd",
      artist: "Alexander van den Bosch",
      year: 1964,
      dimensions: "49x34",
      status: "passepartout",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "93",
      artist: "Alexander van den Bosch",
      title: "Andy Warhol is not dead",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: "94",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: "95",
      title: "Andy Warhol is not dead",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: "96",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: "97",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: "98",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: "99",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: "100",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "101",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "102",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "103",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "104",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "105",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "106",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "107",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "108",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "109",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "110",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "111",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x51",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "112",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x58",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: "31",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "137x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "32",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "33",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "51x57",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: "34",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "48x65",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "35",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "65x48",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "36",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "37",
      artist: "Alexander van den Bosch",
      dimensions: "49x75",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "38",
      artist: "Alexander van den Bosch",
      dimensions: "48x65",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "39",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "68x55",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: "40",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "33x23",
      status: "loose",
      stored: "box 1",
      type: "screenprint",
    },
    {
      id: "41",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "42",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "43",
      artist: "Alexander van den Bosch",
      year: 1971,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "44",
      artist: "Alexander van den Bosch",
      title: "Zonder titel",
      year: 1974,
      dimensions: "75x53",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "113",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x53",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "114",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "115",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "116",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "48x65",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "117",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "118",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "76x54",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "119",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "76x52",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "120",
      artist: "Alexander van den Bosch",
      year: 1965,
      dimensions: "63x49",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "121",
      artist: "Alexander van den Bosch",
      year: 1968,
      dimensions: "62x45",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "122",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "123",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "83x63",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "124",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "125",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "63x52",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "126",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "77x57",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "127",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "128",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "129",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "130",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "69x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "131",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "77x58",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "132",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "74x54",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "133",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "58x78",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: "134",
      artist: "Alexander van den Bosch",
      title: "Inferno 3",
      year: 1987,
      dimensions: "64x49",
      status: "framed",
      type: "drawing",
    },
    {
      id: "135",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      stored: "box 2",
      type: "oilpainting",
    },
    {
      id: "136",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      stored: "box 2",
      type: "oilpainting",
    },
    {
      id: "137",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "138",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "139",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "140",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "141",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "142",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x57",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "143",
      dimensions: "55x38",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "144",
      artist: "Alexander van den Bosch",
      year: 1972,
      dimensions: "65x47",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "145",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "60x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "146",
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "65x39",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "147",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x58",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "148",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "149",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "76x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "150",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "76x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "151",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "48x35",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "152",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x58",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "153",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "154",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "77x58",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "155",
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: "156",
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
  ];

  getPaintings(): Painting[] {
    return this.paintings;
  }
}
