import { Injectable } from "@angular/core";
import { Painting } from "../models/painting";

@Injectable({
  providedIn: "root",
})
export class PaintingService {
  getNextImageUrl(imageId: number): string {
    const paintings = this.getPaintings();
    const currentIndex = paintings.findIndex((p) => p.id === imageId);
    const nextIndex = (currentIndex + 1) % paintings.length;
    const nextPainting = this.getPaintings()[nextIndex];
    if (nextPainting && nextPainting.id !== undefined) {
      return "/image/" + nextPainting.id;
    }
    return "/image/0";
  }

  getPrevImageUrl(imageId: number): string {
    const paintings = this.getPaintings();
    const currentIndex = paintings.findIndex((p) => p.id === imageId);
    const prevIndex = (currentIndex - 1 + paintings.length) % paintings.length;
    const prevPainting = paintings[prevIndex];
    if (prevPainting && prevPainting.id !== undefined) {
      return "/image/" + prevPainting.id;
    }
    return "/image/0";
  }

  private paintings: Painting[] = [
    {
      id: 46,
      title: "Andy Warhol is not dead",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "50x64",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 47,
      title: "Oranje figuur",
      artist: "Alexander van den Bosch",
      year: 1985,
      dimensions: "75x54",
      status: "framed",
      type: "drawing",
    },
    {
      id: 1,
      artist: "Alexander van den Bosch",
      dimensions: "100x120",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 2,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "100x138",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 48,
      title: "Inferno 4",
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "64x50",
      status: "framed",
      type: "drawing",
    },
    {
      id: 49,
      artist: "Alexander van den Bosch",
      dimensions: "54x74",
      status: "framed",
      type: "oilpainting",
      note: "Damaged glass",
    },
    {
      id: 50,
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "47x58",
      status: "framed",
      type: "drawing",
      note: "Damaged glass",
    },
    {
      id: 51,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x56",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 52,
      artist: "Alexander van den Bosch",
      dimensions: "70x85",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 53,
      title: "Zeilbootje bij kalme zee",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "121x96",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 54,
      title: "De speelgoedhoek",
      artist: "Alexander van den Bosch",
      year: 1984,
      dimensions: "121x100",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 55,
      title: "IJshockiers",
      artist: "Alexander van den Bosch",
      year: 1984,
      dimensions: "100x120",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 56,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x140",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 57,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x140",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 3,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 4,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "139x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 5,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "102x141",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 6,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "102x120",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 7,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 8,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 9,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "121x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 10,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "140x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 11,
      artist: "Alexander van den Bosch",
      dimensions: "100x140",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 12,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "121x102",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 14,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "139x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 13,
      artist: "Alexander van den Bosch",
      dimensions: "141x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 15,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 16,
      artist: "Alexander van den Bosch",
      dimensions: "138x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 17,
      artist: "Alexander van den Bosch",
      dimensions: "126x96",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 18,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 19,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "141x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 20,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 21,
      artist: "Alexander van den Bosch",
      year: 1964,
      dimensions: "137x110",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 22,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "112x112",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 23,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "120x103",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 24,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "118x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 25,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "111x70",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 26,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "110x135",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 27,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "118x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 58,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: 59,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: 60,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "32x43",
      status: "framed",
      type: "etching",
    },
    {
      id: 61,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 62,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 63,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 64,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 65,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 66,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "75x54",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 67,
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "75x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 68,
      title: "Fantomas cinema",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "passepartout",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 69,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "91x63",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 70,
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 71,
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "framed",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 72,
      title: "Compositie in oranje rood",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 73,
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 74,
      title: "Oranje figuren",
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "76x50",
      status: "passepartout",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 75,
      title: "Fantomas cinema",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "47x63",
      status: "passepartout",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 76,
      title: "Landschap na zonsondergang",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 77,
      title: "Bloesemboompjes",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 78,
      title: "Veulen met jong bij onweer",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "64x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 79,
      title: "Landschap bij zonnig weer",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 80,
      title: "Vier marionetten",
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "56x39",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 81,
      title: "Landschap met oude molen",
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "framed",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 82,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 83,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 84,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 85,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 86,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 87,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 88,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 89,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 90,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "56x76",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 91,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "76x56",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 92,
      title: "Muze bevredigd",
      artist: "Alexander van den Bosch",
      year: 1964,
      dimensions: "49x34",
      status: "passepartout",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 93,
      artist: "Alexander van den Bosch",
      title: "Andy Warhol is not dead",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: 94,
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: 95,
      title: "Andy Warhol is not dead",
      artist: "Alexander van den Bosch",
      year: 1988,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: 96,
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: 97,
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: 98,
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: 99,
      artist: "Alexander van den Bosch",
      year: 1987,
      dimensions: "66x51",
      status: "loose",
      stored: "box 1",
      type: "drawing",
    },
    {
      id: 100,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 101,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 102,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 103,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 104,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 105,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 106,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 107,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 108,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 109,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 110,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x56",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 111,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x51",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 112,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x58",
      status: "loose",
      stored: "box 1",
      type: "oilpainting",
    },
    {
      id: 31,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "137x100",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 32,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "120x101",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 33,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "51x57",
      status: "rolled",
      type: "oilpainting",
    },
    {
      id: 34,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "48x65",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 35,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "65x48",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 36,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 37,
      artist: "Alexander van den Bosch",
      dimensions: "49x75",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 38,
      artist: "Alexander van den Bosch",
      dimensions: "48x65",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 39,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "68x55",
      status: "loose",
      stored: "box 1",
      type: "gouache",
    },
    {
      id: 40,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "33x23",
      status: "loose",
      stored: "box 1",
      type: "screenprint",
    },
    {
      id: 41,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 42,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 43,
      artist: "Alexander van den Bosch",
      year: 1971,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 44,
      artist: "Alexander van den Bosch",
      title: "Zonder titel",
      year: 1974,
      dimensions: "75x53",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 113,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x53",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 114,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 115,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 116,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "48x65",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 117,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 118,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "76x54",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 119,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "76x52",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 120,
      artist: "Alexander van den Bosch",
      year: 1965,
      dimensions: "63x49",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 121,
      artist: "Alexander van den Bosch",
      year: 1968,
      dimensions: "62x45",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 122,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 123,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "83x63",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 124,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 125,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "63x52",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 126,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "77x57",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 127,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 128,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 129,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 130,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "69x55",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 131,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "77x58",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 132,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "74x54",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 133,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "58x78",
      status: "loose",
      stored: "box 1",
      type: "goauche",
    },
    {
      id: 134,
      artist: "Alexander van den Bosch",
      title: "Inferno 3",
      year: 1987,
      dimensions: "64x49",
      status: "framed",
      type: "drawing",
    },
    {
      id: 135,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      stored: "box 2",
      type: "oilpainting",
    },
    {
      id: 136,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      stored: "box 2",
      type: "oilpainting",
    },
    {
      id: 137,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 138,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 139,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 140,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 141,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 142,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "78x57",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 143,
      dimensions: "55x38",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 144,
      artist: "Alexander van den Bosch",
      year: 1972,
      dimensions: "65x47",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 145,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "60x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 146,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "65x39",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 147,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x58",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 148,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 149,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "76x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 150,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "76x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 151,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "48x35",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 152,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x58",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 153,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "78x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 154,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "77x58",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 155,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 156,
      artist: "Alexander van den Bosch",
      year: 1977,
      dimensions: "77x56",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 157,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 158,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "69x47",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 159,
      artist: "Alexander van den Bosch",
      dimensions: "38x55",
      status: "loose",
      stored: "box 2",
      type: "drawing",
    },
    {
      id: 160,
      artist: "Alexander van den Bosch",
      dimensions: "38x55",
      status: "loose",
      stored: "box 2",
      type: "drawing",
    },
    {
      id: 161,
      artist: "Alexander van den Bosch",
      dimensions: "54x53",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 162,
      artist: "Alexander van den Bosch",
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 163,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 164,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 165,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 166,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 167,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 168,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "60x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 169,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x49",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 170,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 171,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 172,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 173,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 174,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "66x51",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 175,
      artist: "Alexander van den Bosch",
      year: 1974,
      title: "Oranje rotsen",
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 176,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 177,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 178,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 179,
      artist: "Alexander van den Bosch",
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 180,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x51",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 181,
      artist: "Alexander van den Bosch",
      year: 1976,
      title: "Fantomas cinema",
      dimensions: "65x51",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 182,
      artist: "Alexander van den Bosch",
      title: "Fantomas cinema",
      year: 1976,
      dimensions: "65x49",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 183,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x49",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 184,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 185,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 186,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "77x57",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 187,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 188,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 189,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 190,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 191,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 192,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 193,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 194,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x49",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 195,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 196,
      artist: "Alexander van den Bosch",
      dimensions: "65x48",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 197,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 198,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 199,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 200,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 201,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "55x35",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 202,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 203,
      artist: "Alexander van den Bosch",
      dimensions: "75x55",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 204,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "69x52",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 205,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "69x52",
      status: "loose",
      stored: "box 2",
      type: "gouache",
    },
    {
      id: 206,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "54x74",
      status: "framed",
      type: "oilpainting",
    },
    {
      id: 207,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 208,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 209,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 210,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 211,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 212,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 213,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 214,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 215,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 216,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 217,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 218,
      artist: "Alexander van den Bosch",
      year: 1980,
      dimensions: "100x120",
      status: "loose",
      type: "oilpainting",
    },
    {
      id: 219,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "77x58",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 220,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "78x59",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 221,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "78x56",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 222,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "78x58",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 223,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "78x56",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 224,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "78x56",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 225,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "78x56",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 226,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 227,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 228,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 229,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 230,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 231,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 232,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 233,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 234,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "63x52",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 235,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x53",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 236,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 237,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 238,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 239,
      artist: "Alexander van den Bosch",
      year: 1975,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 240,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 241,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x55",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 242,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x48",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 243,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x48",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 244,
      artist: "Alexander van den Bosch",
      year: 1974,
      dimensions: "75x48",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 245,
      artist: "Alexander van den Bosch",
      year: 1983,
      dimensions: "77x57",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 246,
      artist: "Alexander van den Bosch",
      year: 1983,
      dimensions: "77x57",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 247,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "65x48",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 248,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "77x58",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 249,
      artist: "Alexander van den Bosch",
      year: 1973,
      dimensions: "68x47",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 250,
      artist: "Alexander van den Bosch",
      year: 1976,
      dimensions: "63x47",
      status: "loose",
      type: "gouache",
      stored: "box 4",
    },
    {
      id: 251,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 252,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 253,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 254,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 255,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 256,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 257,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 258,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 259,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 260,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 261,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 262,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 263,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 264,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 265,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 266,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 267,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 268,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 269,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 270,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 271,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 272,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 273,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 274,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 275,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 276,
      artist: "Alexander van den Bosch",
      year: 1981,
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 277,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      type: "gouache",
      stored: "box 6",
    },
    {
      id: 278,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      type: "gouache",
      stored: "box 6",
    },
    {
      id: 279,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      type: "gouache",
      stored: "box 6",
    },
    {
      id: 280,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      type: "gouache",
      stored: "box 6",
    },
    {
      id: 281,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      type: "gouache",
      stored: "box 6",
    },
    {
      id: 282,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      type: "gouache",
      stored: "box 6",
    },
    {
      id: 283,
      artist: "Alexander van den Bosch",
      year: 1978,
      dimensions: "108x75",
      status: "loose",
      type: "gouache",
      stored: "box 6",
    },
    {
      id: 284,
      artist: "Alexander van den Bosch",
      year: 1979,
      dimensions: "78x56",
      status: "loose",
      type: "gouache",
      stored: "box 5",
    },
    {
      id: 285,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 286,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 287,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 288,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 289,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 290,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 291,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 292,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 293,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 294,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 295,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 296,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 297,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 298,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 299,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 300,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
    {
      id: 301,
      artist: "Alexander van den Bosch",
      dimensions: "30x40",
      status: "loose",
      type: "etching",
      stored: "box 5",
    },
  ];

  getPaintings(): Painting[] {
    this.paintings.sort((a, b) => a.id - b.id);
    return this.paintings;
  }
}
